platform :ios, '7.0'
pod 'MMDrawerController', '~> 0.5.7'
pod 'MWFeedParser'
pod 'UzysAnimatedGifPullToRefresh', '~> 0.9.5'
pod 'TMCache', '~> 1.2.4'
pod 'SDWebImage', '~>3.7'
pod 'XMLDictionary', '~> 1.4'
